#!/usr/bin/env node
// Fetches emoji data from iamcal/emoji-data and generates src/emoji-data.js
// Source: https://github.com/iamcal/emoji-data

import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(__dirname, "..", "src", "emoji-data.js");

const EMOJI_JSON_URL =
  "https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json";

async function main() {
  console.log("Fetching emoji data from iamcal/emoji-data...");
  const res = await fetch(EMOJI_JSON_URL);
  if (!res.ok) throw new Error(`Failed to fetch: ${res.status}`);
  const data = await res.json();

  // entries: [short_name, unified_code] — one per emoji (primary short_name only)
  const entries = [];
  // aliases: { alias_name: unified_code } — only for non-primary short_names
  const aliases = {};

  for (const emoji of data) {
    if (!emoji.has_img_apple) continue; // skip emoji without common rendering

    const code = emoji.unified;
    const primary = emoji.short_name;

    entries.push([primary, code]);

    // add non-primary short_names as aliases
    if (emoji.short_names) {
      for (const alias of emoji.short_names) {
        if (alias !== primary) {
          aliases[alias] = code;
        }
      }
    }
  }

  console.log(
    `Generated ${entries.length} entries, ${Object.keys(aliases).length} aliases`,
  );

  const skinIdsToCodes = {
    "skin-tone-1": "1F3FB",
    "skin-tone-2": "1F3FC",
    "skin-tone-3": "1F3FD",
    "skin-tone-4": "1F3FE",
    "skin-tone-5": "1F3FF",
  };

  const output = `// Generated by scripts/build-emoji.js from https://github.com/iamcal/emoji-data
// Do not edit manually — run: node scripts/build-emoji.js

const entries = ${JSON.stringify(entries)};

const aliases = ${JSON.stringify(aliases)};

const skinIdsToCodes = ${JSON.stringify(skinIdsToCodes)};

export { entries, aliases, skinIdsToCodes };
`;

  writeFileSync(OUTPUT, output);
  console.log(`Written to ${OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
